test:
  message: "YML LOADED"


server:
  port: 8080

spring:
  application:
    name: shop

  devtools:
    livereload:
      enabled: true           # 자동 리로드 설정
    restart:
      enabled: true           # 자동 재실행 설정

  thymeleaf:
    cache: false              # 캐쉬 없음




  ####################################
  # MySql Setting
  ####################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME} #dain0127
    password: ${DB_PASSWORD} #1234

  ####################################
  # JPA Setting
  ###0#################################
  jpa:
    open-in-view: true      #
    hibernate:
      ddl-auto: update      # create, update, none, create-drop, validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true          # SQL ?? ???
    properties:
      hibernate:
        format_sql: true    # ?? ???? ???
  #  database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8 ?? ??


  ####################################
  # Security User
  ####################################
  security:
    user:
      name: test@test.com
      password: 1111

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


####################################
# 사용자 경로
####################################
itemImgLocation: C:/Users/dain0/Desktop/developer/web/WEB_3_java_shop/item_img_save
uploadPath : file:///C:/Users/dain0/Desktop/developer/web/WEB_3_java_shop/

mainBannerImgLocation: C:/Users/dain0/Desktop/developer/web/WEB_3_java_shop/image_sample/banner


####################################
# 로그 정보 설정
####################################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # 물음표에 바인드 파라미터 출력


####################################
# 포트원 데이터에 접속하기 위한 api 사용 key
####################################
portone:
  api-secret: V69a0sDpAtNf2gXVhgQROCN3esJlb6Kion727KceFTMAtHtlJp1h1woBuWfbwXYKl70m1MNI8g87Fczc

discord:
  webhook:
    url: https://discord.com/api/webhooks/1455465402162483256/zneTNO9OiPfEKMy4B_Rreq6blez6m3TTwb83WSr6Z77GPDiEqpVZHiLC9nUn_T3LcsRy

